### ISSUE TITLE
Allow to only rebuild specified dir 

### ISSUE THREAD

**Issue by foxriver76** [AlCalzone/pak#5]
https://github.com/ioBroker/ioBroker.js-controller/issues/831#issuecomment-982824128

Npm npm rebuild itself only takes path up from v7 thus I guess changing the cwd and then firing rebuild ist the better option

**Comment by foxriver76** [comment]
It can be defined by creating a new PAckageManger and passing cwd accordingly

**Comment by AlCalzone** [comment]
> up from v7

I'm pretty sure i did my tests with npm6. The requirement though is having no package-lock.json in the adapter directories, which will exist if `npm install` was called in an adapter directory.

> creating a new PAckageManger and passing cwd accordingly

You're right, just set `cwd` to the adapter dir. Or if an instance of the package manager already exists, we could temporarily change cwd for this action.
